In [65]:
import os
import glob
import pandas as pd
import numpy as np
import seaborn as sns

main_directory = os.path.normpath(os.getcwd())

file = os.path.join(main_directory, 'all_team_data.csv')
team_data = pd.read_csv(file)

file = os.path.join(main_directory, '2024_team_data.csv')
team_2024_data = pd.read_csv(file)

team_2024_data.set_index(team_2024_data.columns[0], inplace=True) 
team_data.set_index(team_data.columns[0], inplace=True) 
team_data.head()
team_2024_data.head()

FG   FGA    FG%    3P   3PA    3P%    2P   2PA  \
Team                                                                       
Atlanta Hawks 2024      43.2  92.6  0.466  13.8  37.6  0.366  29.4  55.0   
Boston Celtics 2024     43.8  90.2  0.486  16.6  42.6  0.390  27.2  47.6   
Brooklyn Nets 2024      41.0  89.6  0.457  13.4  37.2  0.362  27.5  52.4   
Charlotte Hornets 2024  40.1  87.5  0.458  11.8  33.5  0.351  28.3  54.1   
Chicago Bulls 2024      41.8  89.6  0.467  11.6  32.5  0.358  30.2  57.1   

                          2P%    FT   FTA    FT%   ORB   DRB   TRB   AST  STL  \
Team                                                                            
Atlanta Hawks 2024      0.535  19.1  23.8  0.803  12.8  31.9  44.7  26.5  7.6   
Boston Celtics 2024     0.572  16.9  20.9  0.807  10.7  35.7  46.4  26.6  6.6   
Brooklyn Nets 2024      0.525  15.7  20.7  0.759  11.5  32.4  43.9  26.2  6.9   
Charlotte Hornets 2024  0.524  14.4  18.5  0.781   9.7  31.0  40.7  24.5  6.8   
Chicago Bulls 2024      0.529  16.9  21.2  0.795  11.0  32.5  43.6  25.1  7.6   

                        BLK   TOV    PF    PTS  Opp FG  Opp FGA  Opp FG%  \
Team                                                                       
Atlanta Hawks 2024      4.6  13.3  18.4  119.2    44.7     90.4    0.494   
Boston Celtics 2024     6.5  12.0  16.5  121.1    41.5     91.6    0.454   
Brooklyn Nets 2024      5.1  13.0  18.7  111.0    41.6     88.2    0.471   
Charlotte Hornets 2024  4.5  13.8  18.2  106.3    43.1     87.4    0.494   
Chicago Bulls 2024      4.8  12.1  18.8  112.2    41.0     87.2    0.470   

                        Opp 3P  Opp 3PA  Opp 3P%  Opp 2P  Opp 2PA  Opp 2P%  \
Team                                                                         
Atlanta Hawks 2024        14.0     36.4    0.384    30.7     54.0    0.569   
Boston Celtics 2024       12.8     36.6    0.350    28.7     55.0    0.523   
Brooklyn Nets 2024        12.9     34.6    0.373    28.7     53.6    0.535   
Charlotte Hornets 2024    13.5     35.9    0.377    29.6     51.5    0.575   
Chicago Bulls 2024        14.5     39.8    0.365    26.5     47.4    0.559   

                        Opp FT  Opp FTA  Opp FT%  Opp ORB  Opp DRB  Opp TRB  \
Team                                                                          
Atlanta Hawks 2024        17.2     21.9    0.787     10.9     33.3     44.3   
Boston Celtics 2024       13.7     17.8    0.767     11.0     32.2     43.2   
Brooklyn Nets 2024        17.5     21.6    0.808     10.2     34.0     44.2   
Charlotte Hornets 2024    16.9     21.2    0.799     10.4     34.9     45.3   
Chicago Bulls 2024        17.0     21.8    0.781     10.3     33.5     43.8   

                        Opp AST  Opp STL  Opp BLK  Opp TOV  Opp PF  Opp PTS  \
Team                                                                          
Atlanta Hawks 2024         28.3      7.6      5.7     14.2    19.6    120.5   
Boston Celtics 2024        24.9      6.2      3.7     11.9    17.9    109.6   
Brooklyn Nets 2024         25.4      6.8      4.8     12.8    18.2    113.5   
Charlotte Hornets 2024     28.5      7.1      5.0     13.7    17.5    116.8   
Chicago Bulls 2024         28.0      6.7      5.0     14.0    19.0    113.6   

                         Age        W%       PW%    MOV   SOS    SRS   ORtg  \
Team                                                                          
Atlanta Hawks 2024      26.2  0.458333  0.458333  -1.29 -0.36  -1.65  118.3   
Boston Celtics 2024     28.3  0.791667  0.805556  11.54 -0.40  11.14  123.5   
Brooklyn Nets 2024      26.3  0.383562  0.424658  -2.51 -0.07  -2.57  113.6   
Charlotte Hornets 2024  25.2  0.250000  0.208333 -10.43 -0.26 -10.69  108.8   
Chicago Bulls 2024      28.0  0.479452  0.452055  -1.40 -0.33  -1.73  114.7   

                         DRtg  NRtg   Pace    FTr   3PAr    TS%   eFG%  TOV%  \
Team                                                                           
Atlanta Hawks 2024     

In [52]:

X = team_data.copy()
X = X.drop(columns=['W'])
display(X)
y = team_data['W']

print(X.columns)
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns', None)

#sns.pairplot(team_data[['W%','ORtg', 'DRtg', 'NRtg', 'Pace', 'FTr', '3PAr', 'TS%','W']])
result = team_data[team_data['W'] > 11]
# Display the filtered result


FG   FGA    FG%    3P   3PA    3P%  \
Team                                                                           
Atlanta Hawks 2000                      36.6  83.0  0.441   3.1   9.9  0.317   
Boston Celtics 2000                     37.2  83.9  0.444   5.1  15.4  0.331   
Charlotte Hornets 2000                  35.8  79.7  0.449   4.1  12.2  0.339   
Chicago Bulls 2000                      31.3  75.4  0.415   4.1  12.6  0.329   
Cleveland Cavaliers 2000                36.3  82.1  0.442   4.2  11.2  0.373   
Dallas Mavericks 2000                   39.0  85.9  0.453   6.3  16.2  0.391   
Denver Nuggets 2000                     37.3  84.3  0.442   5.7  17.0  0.336   
Detroit Pistons 2000                    37.1  80.9  0.459   5.4  14.9  0.359   
Golden State Warriors 2000              36.5  87.1  0.420   4.2  13.0  0.323   
Houston Rockets 2000                    36.6  81.3  0.450   7.1  19.8  0.358   
Indiana Pacers 2000                     37.2  81.0  0.459   7.1  18.1  0.392   
Los Angeles Clippers 2000               35.1  82.4  0.426   5.2  15.5  0.339   
Los Angeles Lakers 2000                 38.3  83.4  0.459   4.2  12.8  0.329   
Miami Heat 2000                         36.3  78.8  0.460   5.4  14.7  0.371   
Milwaukee Bucks 2000                    38.7  83.3  0.465   4.8  13.0  0.369   
Minnesota Timberwolves 2000             39.3  84.3  0.467   3.0   8.7  0.346   
New Jersey Nets 2000                    36.3  83.9  0.433   5.8  16.8  0.347   
New York Knicks 2000                    35.3  77.7  0.455   4.3  11.4  0.375   
Orlando Magic 2000                      38.6  85.5  0.452   3.6  10.6  0.338   
Philadelphia 76ers 2000                 36.5  82.6  0.442   2.5   7.8  0.323   
Phoenix Suns 2000                       37.7  82.6  0.457   5.6  15.2  0.368   
Portland Trail Blazers 2000             36.8  78.4  0.470   5.0  13.8  0.361   
Sacramento Kings 2000                   40.0  88.9  0.450   6.5  20.2  0.322   
San Antonio Spurs 2000                  36.0  78.0  0.462   4.0  10.8  0.374   
Seattle Supersonics 2000                37.9  84.7  0.447   6.7  19.6  0.339   
Toronto Raptors 2000                    36.3  83.9  0.433   5.2  14.3  0.363   
Utah Jazz 2000                          36.1  77.8  0.464   4.0  10.4  0.385   
Vancouver Grizzlies 2000                35.3  78.5  0.449   4.0  11.0  0.361   
Washington Wizards 2000                 36.7  81.5  0.451   4.1  10.9  0.376   
Atlanta Hawks 2001                      35.1  81.3  0.431   4.1  11.4  0.357   
Boston Celtics 2001                     33.8  79.1  0.428   7.2  19.9  0.363   
Charlotte Hornets 2001                  34.1  79.3  0.431   4.1  12.0  0.346   
Chicago Bulls 2001                      33.2  78.2  0.424   4.0  11.6  0.346   
Cleveland Cavaliers 2001                35.2  79.7  0.442   2.7   8.0  0.334   
Dallas Mavericks 2001                   37.6  81.9  0.459   6.3  16.5  0.381   
Denver Nuggets 2001                     36.3  83.9  0.433   6.2  17.6  0.355   
Detroit Pistons 2001                    35.6  83.9  0.424   4.7  13.6  0.350   
Golden State Warriors 2001              35.8  87.5  0.409   3.4  11.8  0.293   
Houston Rockets 2001                    35.9  79.2  0.453   6.1  17.2  0.357   
Indiana Pacers 2001                     34.5  78.4  0.440   4.8  14.1  0.342   
Los Angeles Clippers 2001               35.3  78.9  0.448   4.4  13.0  0.339   
Los Angeles Lakers 2001                 37.9  81.5  0.465   5.4  15.5  0.344   
Miami Heat 2001                         32.9  76.3  0.430   5.8  16.9  0.345   
Milwaukee Bucks 2001                    38.0  82.9  0.458   6.9  18.1  0.379   
Minnesota Timberwolves 2001             38.4  83.8  0.458   3.9  11.0  0.357   
New Jersey Nets 2001                    33.9  79.9  0.425   4.4  13.2  0.333   
New York Knicks 2001                    33.6  75.6  0.444   4.8  13.6  0.351   
Orlando Magic 2001                      36.7  83.8  0.438   6.0  16.4  0.364   
Philadelphia 76ers 2001                 35

Index(['FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'FT', 'FTA',
       'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'Opp FG', 'Opp FGA', 'Opp FG%', 'Opp 3P', 'Opp 3PA', 'Opp 3P%',
       'Opp 2P', 'Opp 2PA', 'Opp 2P%', 'Opp FT', 'Opp FTA', 'Opp FT%',
       'Opp ORB', 'Opp DRB', 'Opp TRB', 'Opp AST', 'Opp STL', 'Opp BLK',
       'Opp TOV', 'Opp PF', 'Opp PTS', 'Age', 'W%', 'PW%', 'MOV', 'SOS', 'SRS',
       'ORtg', 'DRtg', 'NRtg', 'Pace', 'FTr', '3PAr', 'TS%', 'eFG%', 'TOV%',
       'ORB%', 'FT/FGA', 'Opp eFG%', 'Opp TOV%', 'DRB%', 'Opp FT/FGA'],
      dtype='object')


In [53]:
from sklearn import tree, svm, metrics
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.datasets import load_digits
from sklearn.preprocessing import scale

import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['figure.figsize'] = (10, 6)
plt.style.use('ggplot')

In [61]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, test_size=0.8)

model = svm.SVC(kernel='rbf', C=243)

model.fit(X_train, y_train)   

y_pred = model.predict(X_test)

# Get indices of instances classified as 1
champ_i = np.where(y_pred == 16)[0]

# Select teams classified as 1 from the DataFrame
index = y_test.iloc[champ_i].index
shoulda_won = team_data.loc[index]
shoulda_won = shoulda_won[['W','W%','NRtg']]
display(shoulda_won)

print('Confusion Matrix:')
print(metrics.confusion_matrix(y_true = y_test, y_pred = y_pred))

print('Accuracy = ', metrics.accuracy_score(y_true = y_test, y_pred = y_pred))

W        W%  NRtg
Team                                            
San Antonio Spurs 2003      16.0  0.731707   5.9
San Antonio Spurs 2002       4.0  0.707317   6.8
Golden State Warriors 2016  15.0  0.890244  10.7
Boston Celtics 2008         16.0  0.804878  11.3
San Antonio Spurs 2006       7.0  0.768293   7.7
San Antonio Spurs 2001       7.0  0.707317   8.6
Chicago Bulls 2012           2.0  0.757576   9.1
Detroit Pistons 2004        16.0  0.658537   6.6
San Antonio Spurs 2016       6.0  0.817073  11.3
Boston Celtics 2011          5.0  0.682927   5.9

Confusion Matrix:
[[288   0   1   0   1   0   2   4   0   0   0   1   0   0   0   0   0]
 [ 33   2   5   1   1   0   0   5   0   0   0   1   0   0   0   0   0]
 [ 29   1   6   1   1   0   4   5   0   0   2   0   0   0   0   0   1]
 [ 19   2   1   0   0   0   2   2   0   0   0   0   0   0   0   0   0]
 [  6   3   0   0   1   0   0   3   0   0   0   1   0   0   0   0   1]
 [  9   0   0   1   0   0   2   1   0   0   0   0   0   0   0   0   1]
 [ 12   1   4   0   2   0   3   2   0   0   1   0   0   0   0   0   1]
 [  4   2   0   0   1   0   0   3   0   0   1   2   0   0   0   0   2]
 [  1   0   1   0   0   0   1   3   0   0   0   0   0   0   0   0   0]
 [  5   1   1   1   0   0   2   1   0   0   0   0   0   0   0   0   0]
 [  1   2   3   1   2   1   1   4   0   0   2   1   0   0   0   0   0]
 [  1   0   0   0   2   0   3   1   0   0   0   0   0   0   0   0   0]
 [  1   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  2   1   1   0   0   0   0   1   0   0   1   0   0   0  

In [62]:
C_values = np.linspace(1, 400, 100)
accuracies = {}
for C in C_values:
    modelC = svm.SVC(kernel='rbf', C=C)
    
    scores = cross_val_score(modelC, X, y, cv=5)
    
    mean_accuracy = np.mean(scores)
    
    accuracies[C] = mean_accuracy

best_C = max(accuracies, key=accuracies.get)
best_accuracy = accuracies[best_C]

print("Best C: " , best_C)
print("Accuracy = ",best_accuracy)

/opt/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(
/opt/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(
/opt/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(
/opt/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(
/opt/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(
/opt/anaconda3/lib/python

Best C:  142.06060606060606
Accuracy =  0.5510489510489511


In [69]:

X_data = team_2024_data.copy()
X_data.drop(X_data.tail(1).index, inplace=True)

model1 = svm.SVC(kernel='rbf', C=200)

model1.fit(X, y)   

playoff_wins = model1.predict(X_data)
place = ['Champion','Finals','Conference Finals','2nd Round','1st round','Missed Playoffs']

NBA_2024 = pd.DataFrame(X_data['W%'])
NBA_2024.insert(1, 'Playoff Wins', playoff_wins)
NBA_2024.sort_values(by=['Playoff Wins','W%'], ascending=[False, False],inplace=True)

display(NBA_2024)

W%  Playoff Wins
Team                                               
Boston Celtics 2024          0.791667          16.0
Minnesota Timberwolves 2024  0.694444          16.0
Oklahoma City Thunder 2024   0.694444           7.0
New Orleans Pelicans 2024    0.611111           7.0
New York Knicks 2024         0.611111           2.0
Denver Nuggets 2024          0.698630           1.0
Milwaukee Bucks 2024         0.638889           1.0
Los Angeles Clippers 2024    0.625000           0.0
Cleveland Cavaliers 2024     0.602740           0.0
Dallas Mavericks 2024        0.597222           0.0
Phoenix Suns 2024            0.589041           0.0
Orlando Magic 2024           0.583333           0.0
Sacramento Kings 2024        0.583333           0.0
Los Angeles Lakers 2024      0.561644           0.0
Indiana Pacers 2024          0.554054           0.0
Miami Heat 2024              0.541667           0.0
Philadelphia 76ers 2024      0.534247           0.0
Golden State Warriors 2024   0.527778           0.0
Houston Rockets 2024         0.513889           0.0
Chicago Bulls 2024           0.479452           0.0
Atlanta Hawks 2024           0.458333           0.0
Utah Jazz 2024               0.397260           0.0
Brooklyn Nets 2024           0.383562           0.0
Memphis Grizzlies 2024       0.328767           0.0
Toronto Raptors 2024         0.315068           0.0
Portland Trail Blazers 2024  0.260274           0.0
Charlotte Hornets 2024       0.250000           0.0
San Antonio Spurs 2024       0.232877           0.0
Washington Wizards 2024      0.191781           0.0
Detroit Pistons 2024         0.164384           0.0

In [41]:
normalized_team = team_stats_dfs[0].copy

team_column = normalized_team['Team']
normalized_team = normalized_team.drop(normalized_team.columns[0], axis=1)

avg_W_perc = normalized_team['W%'].mean()
avg_W = normalized_team['W'].mean()

normalized_team.at[29,'W%'] = avg_W_perc
normalized_team.at[29,'NRtg'] = 1
normalized_team.at[29,'MOV'] = 1
normalized_team.at[29,'SOS'] = 1
normalized_team.at[29,'SRS'] = 1
normalized_team.at[29,'W'] = avg_W

divisor_row = normalized_team.iloc[29]
normalized_team = normalized_team.div(divisor_row, axis=1)
normalized_team.insert(0, 'Team', team_column)
normalized_team

Team        FG       FGA       FG%        3P  \
0            Atlanta Hawks 2000  0.994565  1.010962  0.982183  0.645833   
1           Boston Celtics 2000  1.010870  1.021924  0.988864  1.062500   
2        Charlotte Hornets 2000  0.972826  0.970767  1.000000  0.854167   
3            Chicago Bulls 2000  0.850543  0.918392  0.924276  0.854167   
4      Cleveland Cavaliers 2000  0.986413  1.000000  0.984410  0.875000   
5         Dallas Mavericks 2000  1.059783  1.046285  1.008909  1.312500   
6           Denver Nuggets 2000  1.013587  1.026797  0.984410  1.187500   
7          Detroit Pistons 2000  1.008152  0.985384  1.022272  1.125000   
8    Golden State Warriors 2000  0.991848  1.060901  0.935412  0.875000   
9          Houston Rockets 2000  0.994565  0.990256  1.002227  1.479167   
10          Indiana Pacers 2000  1.010870  0.986602  1.022272  1.479167   
11    Los Angeles Clippers 2000  0.953804  1.003654  0.948775  1.083333   
12      Los Angeles Lakers 2000  1.040761  1.015834  1.022272  0.875000   
13              Miami Heat 2000  0.986413  0.959805  1.024499  1.125000   
14         Milwaukee Bucks 2000  1.051630  1.014616  1.035635  1.000000   
15  Minnesota Timberwolves 2000  1.067935  1.026797  1.040089  0.625000   
16         New Jersey Nets 2000  0.986413  1.021924  0.964365  1.208333   
17         New York Knicks 2000  0.959239  0.946407  1.013363  0.895833   
18           Orlando Magic 2000  1.048913  1.041413  1.006682  0.750000   
19      Philadelphia 76ers 2000  0.991848  1.006090  0.984410  0.520833   
20            Phoenix Suns 2000  1.024457  1.006090  1.017817  1.166667   
21  Portland Trail Blazers 2000  1.000000  0.954933  1.046771  1.041667   
22        Sacramento Kings 2000  1.086957  1.082826  1.002227  1.354167   
23       San Antonio Spurs 2000  0.978261  0.950061  1.028953  0.833333   
24     Seattle Supersonics 2000  1.029891  1.031669  0.995546  1.395833   
25         Toronto Raptors 2000  0.986413  1.021924  0.964365  1.083333   
26               Utah Jazz 2000  0.980978  0.947625  1.033408  0.833333   
27     Vancouver Grizzlies 2000  0.959239  0.956151  1.000000  0.833333   
28      Washington Wizards 2000  0.997283  0.992692  1.004454  0.854167   
29          League Average 2000  1.000000  1.000000  1.000000  1.000000   

         3PA       3P%        2P       2PA       2P%        FT       FTA  \
0   0.722628  0.898017  1.043750  1.068713  0.978632  0.947368  0.956522   
1   1.124088  0.937677  1.006250  1.001462  1.002137  1.042105  1.047431   
2   0.890511  0.960340  0.990625  0.986842  1.002137  1.194737  1.185771   
3   0.919708  0.932011  0.846875  0.918129  0.923077  0.952632  1.007905   
4   0.817518  1.056657  1.003125  1.036550  0.967949  1.063158  1.063241   
5   1.182482  1.107649  1.018750  1.020468  1.000000  0.905263  0.845850   
6   1.240876  0.951841  0.984375  0.982456  1.002137  0.984211  1.019763   
7   1.087591  1.016997  0.993750  0.964912  1.027778  1.257895  1.209486   
8   0.948905  0.915014  1.009375  1.081871  0.933761  0.963158  1.035573   
9   1.445255  1.014164  0.921875  0.899123  1.025641  1.010526  1.035573   
10  1.321168  1.110482  0.937500  0.918129  1.021368  1.047368  0.968379   
11  1.131387  0.960340  0.934375  0.979532  0.952991  0.873684  0.881423   
12  0.934307  0.932011  1.065625  1.032164  1.029915  1.057895  1.142292   
13  1.072993  1.050992  0.962500  0.937135  1.027778  0.863158  0.881423   
14  0.948905  1.045326  1.059375  1.026316  1.032051  1.000000  0.956522   
15  0.635036  0.980170  1.134375  1.103801  1.027778  0.884211  0.853755   
16  1.226277  0.983003  0.953125  0.982456  0.970085  1.026316  0.984190   
17  0.832117  1.062323  0.968750  0.969298  1.000000  0.905263  0.869565   
18  0.773723  0.957507  1.096875  1.095029  1.000000  1.010526  1.031621   
19  0.569343  0.915014  1.062500  1.093567  0.970085  1.010526  1.071146   
20  1.109489  1.042493  1.003125  0.985380  1.019231  0.942105  0.932806   
21  1.007299  1.022663  0.996