In [4]:
import os
import glob
import pandas as pd
import numpy as np
import seaborn as sns

main_directory = os.path.normpath(os.getcwd())
main_directory = os.path.dirname(main_directory)

data_directory = os.path.join(main_directory, 'team_data')

file = os.path.join(data_directory, 'normal_team_data.csv')
team_data = pd.read_csv(file)

file = os.path.join(data_directory, '2024_normal_data.csv')
team_2024_data = pd.read_csv(file)

team_2024_data.set_index(team_2024_data.columns[0], inplace=True) 
team_data.set_index(team_data.columns[0], inplace=True) 
team_data


FG       FGA       FG%        3P       3PA  \
Team                                                                         
Atlanta Hawks 2000        0.994565  1.010962  0.982183  0.645833  0.722628   
Boston Celtics 2000       1.010870  1.021924  0.988864  1.062500  1.124088   
Charlotte Hornets 2000    0.972826  0.970767  1.000000  0.854167  0.890511   
Chicago Bulls 2000        0.850543  0.918392  0.924276  0.854167  0.919708   
Cleveland Cavaliers 2000  0.986413  1.000000  0.984410  0.875000  0.817518   
...                            ...       ...       ...       ...       ...   
Sacramento Kings 2023     1.038095  0.998867  1.040000  1.121951  1.090643   
San Antonio Spurs 2023    1.026190  1.048698  0.978947  0.902439  0.941520   
Toronto Raptors 2023      0.997619  1.033975  0.966316  0.869919  0.935673   
Utah Jazz 2023            1.011905  1.016988  0.995789  1.081301  1.105263   
Washington Wizards 2023   1.002381  0.984145  1.021053  0.918699  0.926901   

                               3P%        2P       2PA       2P%        FT  \
Team                                                                         
Atlanta Hawks 2000        0.898017  1.043750  1.068713  0.978632  0.947368   
Boston Celtics 2000       0.937677  1.006250  1.001462  1.002137  1.042105   
Charlotte Hornets 2000    0.960340  0.990625  0.986842  1.002137  1.194737   
Chicago Bulls 2000        0.932011  0.846875  0.918129  0.923077  0.952632   
Cleveland Cavaliers 2000  1.056657  1.003125  1.036550  0.967949  1.063158   
...                            ...       ...       ...       ...       ...   
Sacramento Kings 2023     1.022161  1.006757  0.940850  1.069343  1.076087   
San Antonio Spurs 2023    0.955679  1.081081  1.116451  0.965328  0.858696   
Toronto Raptors 2023      0.927978  1.050676  1.096118  0.958029  1.000000   
Utah Jazz 2023            0.977839  0.986486  0.961183  1.021898  1.016304   
Washington Wizards 2023   0.986150  1.043919  1.020333  1.020073  0.956522   

                          ...       TS%      eFG%      TOV%      ORB%  \
Team                      ...                                           
Atlanta Hawks 2000        ...  0.961759  0.962343  0.992958  1.096886   
Boston Celtics 2000       ...  0.994264  0.991632  0.971831  1.051903   
Charlotte Hornets 2000    ...  1.013384  0.993724  0.964789  0.889273   
Chicago Bulls 2000        ...  0.936902  0.926778  1.267606  1.034602   
Cleveland Cavaliers 2000  ...  0.986616  0.979079  1.098592  0.972318   
...                       ...       ...       ...       ...       ...   
Sacramento Kings 2023     ...  1.046472  1.049541  0.960000  0.945833   
San Antonio Spurs 2023    ...  0.953528  0.963303  1.040000  1.066667   
Toronto Raptors 2023      ...  0.955250  0.948624  0.824000  1.158333   
Utah Jazz 2023            ...  1.005164  1.003670  1.064000  1.116667   
Washington Wizards 2023   ...  1.006885  1.009174  1.016000  0.941667   

                            FT/FGA  Opp eFG%  Opp TOV%      DRB%  Opp FT/FGA  \
Team                                                                           
Atlanta Hawks 2000        0.939394  1.006276  0.795775  0.998594    0.848485   
Boston Celtics 2000       1.021645  1.041841  1.112676  1.037975    1.324675   
Charlotte Hornets 2000    1.233766  1.000000  1.028169  1.029536    0.857143   
Chicago Bulls 2000        1.038961  1.012552  1.021127  0.983122    1.038961   
Cleveland Cavaliers 2000  1.060606  0.991632  1.063380  1.001406    1.190476   
...                            ...       ...       ...       ...         ...   
Sacramento Kings 2023     1.081731  1.033028  1.008000  1.015789    0.975962   
San Antonio Spurs 2023    0.817308  1.056881  0.960000  0.985526    0.966346   
Toronto Raptors 2023      0.966346  1.036697  1.224000  1.009211    1.072115   
Utah Jazz 2023            1.004808  0.992661  0.872000  0.989474    0.985577   
Washington Wizards 2023   0.971154  0.990826  0.880000  1.001316    0.932692   

           

In [5]:

X = team_data.copy()
X = X.drop(columns=['W'])
#display(X)
y = team_data['W']

print(X.columns)
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns', 13)


sns.pairplot(team_data)

Index(['FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'FT', 'FTA',
       'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'Opp FG', 'Opp FGA', 'Opp FG%', 'Opp 3P', 'Opp 3PA', 'Opp 3P%',
       'Opp 2P', 'Opp 2PA', 'Opp 2P%', 'Opp FT', 'Opp FTA', 'Opp FT%',
       'Opp ORB', 'Opp DRB', 'Opp TRB', 'Opp AST', 'Opp STL', 'Opp BLK',
       'Opp TOV', 'Opp PF', 'Opp PTS', 'Age', 'W%', 'PW%', 'MOV', 'SOS', 'SRS',
       'ORtg', 'DRtg', 'NRtg', 'Pace', 'FTr', '3PAr', 'TS%', 'eFG%', 'TOV%',
       'ORB%', 'FT/FGA', 'Opp eFG%', 'Opp TOV%', 'DRB%', 'Opp FT/FGA'],
      dtype='object')



KeyboardInterrupt



Error in callback <function _draw_all_if_interactive at 0x131f654e0> (for post_execute), with arguments args (),kwargs {}:


KeyboardInterrupt: 

Error in callback <function flush_figures at 0x135ee2660> (for post_execute), with arguments args (),kwargs {}:



KeyboardInterrupt



In [6]:
from sklearn import tree, svm, metrics
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.datasets import load_digits
from sklearn.preprocessing import scale

import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['figure.figsize'] = (10, 6)
plt.style.use('ggplot')

In [7]:
from sklearn.linear_model import LinearRegression

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, test_size=0.8)

# Create a LinearRegression object
model_test = LinearRegression()

# Fit the model to your data
model_test.fit(X_train, y_train)

y_pred = model_test.predict(X_test)

d = {'Prediction': y_pred,
     'Actual' : y_test}



In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, test_size=0.8)

model = svm.SVC(kernel='rbf', C=1)

model.fit(X_train, y_train)   

y_pred = model.predict(X_test)

# Get indices of instances classified as 1
champ_i = np.where(y_pred == 16)[0]

# Select teams classified as 1 from the DataFrame
index = y_test.iloc[champ_i].index
champions = team_data.loc[index]
champions = champions[['W','W%','NRtg']]
display(champions)

print('Confusion Matrix:')
print(metrics.confusion_matrix(y_true = y_test, y_pred = y_pred))

print('Accuracy = ', metrics.accuracy_score(y_true = y_test, y_pred = y_pred))

print('Average difference = ', np.mean(np.abs(y_pred - y_test)) )

W        W%  NRtg
Team                                            
Golden State Warriors 2016  15.0  0.890244  10.7
Boston Celtics 2008         16.0  0.804878  11.3
San Antonio Spurs 2016       6.0  0.817073  11.3

Confusion Matrix:
[[257   0   0   5   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [ 23   0   0   6   0   0   0   0   6   0   0   0   0   0   0   0   0   0]
 [ 26   0   0  11   0   0   0   0  11   0   0   0   0   0   0   0   0   0]
 [ 26   0   0   6   0   0   0   1  17   0   0   0   0   0   0   0   0   0]
 [ 12   0   0   9   0   0   0   0   5   0   0   0   0   0   0   0   0   0]
 [  5   0   0   1   0   0   0   0   9   0   0   0   0   0   0   0   0   0]
 [  8   0   0   1   0   0   0   0   5   0   0   0   0   0   0   0   0   0]
 [  8   0   0   7   0   0   0   2   8   0   0   0   0   0   0   0   0   1]
 [  2   0   0   3   0   0   0   4   6   0   0   0   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0   1   4   0   0   0   0   0   0   0   0   0]
 [  1   0   0   4   0   0   0   2   4   0   0   0   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0   5  12   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   2   5   0   0   0   0   0   0   0   0   0]
 [  1  

In [9]:
C_values = np.linspace(1, 400, 100)
accuracies = {}
for C in C_values:
    modelC = svm.SVC(kernel='rbf', C=C)
    
    modelC.fit(X_train, y_train)
    
    y_pred = modelC.predict(X_test)
    #scores = cross_val_score(modelC, X, y, cv=5)
    
    #mean_accuracy = np.mean(scores)
    
    accuracies[C] = np.mean(np.abs(y_pred - y_test))

best_C = min(accuracies, key=accuracies.get)
best_accuracy = accuracies[best_C]

print("Best C: " , best_C)
print("Average Difference = ",best_accuracy)

Best C:  1.0
Average Difference =  2.097902097902098


In [10]:

X_data = team_2024_data.copy()
X_data.drop(X_data.tail(1).index, inplace=True)
display(X_data)
display(X)
model1 = svm.SVC(kernel='rbf', C=1)

model1.fit(X, y)   

playoff_wins = model1.predict(X_data)

NBA_2024 = pd.DataFrame(X_data['W%'])
NBA_2024.insert(1, 'Playoff Wins', playoff_wins)
NBA_2024.sort_values(by=['Playoff Wins','W%'], ascending=[False, False],inplace=True)

display(NBA_2024)
display(team_2024_data)

FG       FGA       FG%        3P       3PA  \
Team                                                                            
Atlanta Hawks 2024           1.023697  1.040449  0.981053  1.078125  1.074286   
Boston Celtics 2024          1.037915  1.013483  1.023158  1.296875  1.217143   
Brooklyn Nets 2024           0.971564  1.006742  0.962105  1.046875  1.062857   
Charlotte Hornets 2024       0.950237  0.983146  0.964211  0.921875  0.957143   
Chicago Bulls 2024           0.990521  1.006742  0.983158  0.906250  0.928571   
Cleveland Cavaliers 2024     0.988152  0.979775  1.006316  1.062500  1.065714   
Dallas Mavericks 2024        1.028436  1.010112  1.016842  1.140625  1.125714   
Denver Nuggets 2024          1.040284  0.996629  1.042105  0.890625  0.882857   
Detroit Pistons 2024         0.976303  0.993258  0.981053  0.867187  0.908571   
Golden State Warriors 2024   1.035545  1.037079  0.995789  1.148437  1.122857   
Houston Rockets 2024         0.992891  1.020225  0.970526  0.976562  1.011429   
Indiana Pacers 2024          1.106635  1.039326  1.063158  1.039062  1.008571   
Los Angeles Clippers 2024    1.007109  0.971910  1.035789  1.007812  0.951429   
Los Angeles Lakers 2024      1.035545  0.984270  1.048421  0.921875  0.885714   
Memphis Grizzlies 2024       0.907583  0.985393  0.917895  1.046875  1.100000   
Miami Heat 2024              0.938389  0.961798  0.972632  0.953125  0.951429   
Milwaukee Bucks 2024         1.033175  1.000000  1.031579  1.125000  1.094286   
Minnesota Timberwolves 2024  0.978673  0.958427  1.018947  0.992188  0.931429   
New Orleans Pelicans 2024    1.014218  0.983146  1.029474  0.960938  0.925714   
New York Knicks 2024         0.973934  0.996629  0.974737  1.031250  1.031429   
Oklahoma City Thunder 2024   1.056872  1.005618  1.050526  1.046875  0.980000   
Orlando Magic 2024           0.962085  0.953933  1.006316  0.859375  0.891429   
Philadelphia 76ers 2024      0.978673  1.002247  0.974737  0.914062  0.934286   
Phoenix Suns 2024            1.014218  0.968539  1.044211  0.953125  0.914286   
Portland Trail Blazers 2024  0.938389  1.002247  0.934737  0.914062  0.945714   
Sacramento Kings 2024        1.035545  1.022472  1.010526  1.101562  1.108571   
San Antonio Spurs 2024       0.992891  1.019101  0.972632  0.968750  1.025714   
Toronto Raptors 2024         1.007109  1.008989  0.995789  0.906250  0.948571   
Utah Jazz 2024               1.002370  1.014607  0.987368  1.015625  1.048571   

                                  3P%  ...      ORB%    FT/FGA  Opp eFG%  \
Team                                   ...                                 
Atlanta Hawks 2024           1.000000  ...  1.139918  1.067358  1.043876   
Boston Celtics 2024          1.065574  ...  1.028807  0.968912  0.957952   
Brooklyn Nets 2024           0.989071  ...  1.037037  0.906736  0.996344   
Charlotte Hornets 2024       0.959016  ...  0.897119  0.854922  1.043876   
Chicago Bulls 2024           0.978142  ...  1.020576  0.979275  1.012797   
Cleveland Cavaliers 2024     1.000000  ...  0.962963  0.927461  0.965265   
Dallas Mavericks 2024        1.010929  ...  0.921811  0.994819  1.005484   
Denver Nuggets 2024          1.010929  ...  1.057613  0.896373  0.965265   
Detroit Pistons 2024         0.953552  ...  1.012346  1.020725  1.021938   
Golden State Warriors 2024   1.024590  ...  1.135802  0.896373  0.989031   
Houston Rockets 2024         0.964481  ...  1.037037  1.036269  0.967093   
Indiana Pacers 2024          1.027322  ...  0.967078  0.906736  1.021938   
Los Angeles Clippers 2024    1.057377  ...  1.000000  1.103627  0.996344   
Los Angeles Lakers 2024      1.038251  ...  0.806584  1.124352  1.001828   
Memphis Grizzlies 2024       0.948087  ...  0.946502  0.958549  1.005484   
Miami Heat 2024              1.002732  ...  0.901235  1.088083  1.001828   
Milwaukee Bucks 2024         1.030055  ...  0.893004  1.103627  0.985375   
Minnesota Timberwolves 2024  1.060109  ...  0.962963  1.077720  0.936015   
New

FG       FGA       FG%  \
Team                                                                   
Atlanta Hawks 2000                      0.994565  1.010962  0.982183   
Boston Celtics 2000                     1.010870  1.021924  0.988864   
Charlotte Hornets 2000                  0.972826  0.970767  1.000000   
Chicago Bulls 2000                      0.850543  0.918392  0.924276   
Cleveland Cavaliers 2000                0.986413  1.000000  0.984410   
Dallas Mavericks 2000                   1.059783  1.046285  1.008909   
Denver Nuggets 2000                     1.013587  1.026797  0.984410   
Detroit Pistons 2000                    1.008152  0.985384  1.022272   
Golden State Warriors 2000              0.991848  1.060901  0.935412   
Houston Rockets 2000                    0.994565  0.990256  1.002227   
Indiana Pacers 2000                     1.010870  0.986602  1.022272   
Los Angeles Clippers 2000               0.953804  1.003654  0.948775   
Los Angeles Lakers 2000                 1.040761  1.015834  1.022272   
Miami Heat 2000                         0.986413  0.959805  1.024499   
Milwaukee Bucks 2000                    1.051630  1.014616  1.035635   
Minnesota Timberwolves 2000             1.067935  1.026797  1.040089   
New Jersey Nets 2000                    0.986413  1.021924  0.964365   
New York Knicks 2000                    0.959239  0.946407  1.013363   
Orlando Magic 2000                      1.048913  1.041413  1.006682   
Philadelphia 76ers 2000                 0.991848  1.006090  0.984410   
Phoenix Suns 2000                       1.024457  1.006090  1.017817   
Portland Trail Blazers 2000             1.000000  0.954933  1.046771   
Sacramento Kings 2000                   1.086957  1.082826  1.002227   
San Antonio Spurs 2000                  0.978261  0.950061  1.028953   
Seattle Supersonics 2000                1.029891  1.031669  0.995546   
Toronto Raptors 2000                    0.986413  1.021924  0.964365   
Utah Jazz 2000                          0.980978  0.947625  1.033408   
Vancouver Grizzlies 2000                0.959239  0.956151  1.000000   
Washington Wizards 2000                 0.997283  0.992692  1.004454   
Atlanta Hawks 2001                      0.983193  1.008685  0.972912   
Boston Celtics 2001                     0.946779  0.981390  0.966140   
Charlotte Hornets 2001                  0.955182  0.983871  0.972912   
Chicago Bulls 2001                      0.929972  0.970223  0.957111   
Cleveland Cavaliers 2001                0.985994  0.988834  0.997743   
Dallas Mavericks 2001                   1.053221  1.016129  1.036117   
Denver Nuggets 2001                     1.016807  1.040943  0.977427   
Detroit Pistons 2001                    0.997199  1.040943  0.957111   
Golden State Warriors 2001              1.002801  1.085608  0.923251   
Houston Rockets 2001                    1.005602  0.982630  1.022573   
Indiana Pacers 2001                     0.966387  0.972705  0.993228   
Los Angeles Clippers 2001               0.988796  0.978908  1.011287   
Los Angeles Lakers 2001                 1.061625  1.011166  1.049661   
Miami Heat 2001                         0.921569  0.946650  0.970655   
Milwaukee Bucks 2001                    1.064426  1.028536  1.033860   
Minnesota Timberwolves 2001             1.075630  1.039702  1.033860   
New Jersey Nets 2001                    0.949580  0.991315  0.959368   
New York Knicks 2001                    0.941176  0.937965  1.002257   
Orlando Magic 2001                      1.028011  1.039702  0.988713   
Philadelphia 76ers 2001                 0.991597  0.981390  1.009029   
Phoenix Suns 2001                       1.005602  1.022333  0.984199   
Portland Trail Blazers 2001             1.025210  0.971464  1.056433   
Sacramento Kings 2001                   1.070028  1.054591  1.013544   
San Antonio Spurs 2001                  0.985994  0.947891  1.040632   
Seattle Supersonics 2001                1.033613  1.006203  1.029345   
Toronto Raptor

W%  Playoff Wins
Team                                               
Boston Celtics 2024          0.791667          16.0
Minnesota Timberwolves 2024  0.694444          10.0
Oklahoma City Thunder 2024   0.694444          10.0
Denver Nuggets 2024          0.698630           2.0
Milwaukee Bucks 2024         0.638889           2.0
Los Angeles Clippers 2024    0.625000           2.0
New Orleans Pelicans 2024    0.611111           2.0
New York Knicks 2024         0.611111           2.0
Cleveland Cavaliers 2024     0.602740           2.0
Dallas Mavericks 2024        0.597222           1.0
Phoenix Suns 2024            0.589041           1.0
Orlando Magic 2024           0.583333           1.0
Indiana Pacers 2024          0.554054           1.0
Philadelphia 76ers 2024      0.534247           1.0
Golden State Warriors 2024   0.527778           1.0
Houston Rockets 2024         0.513889           1.0
Sacramento Kings 2024        0.583333          -1.0
Los Angeles Lakers 2024      0.561644          -1.0
Miami Heat 2024              0.541667          -1.0
Chicago Bulls 2024           0.479452          -1.0
Atlanta Hawks 2024           0.458333          -1.0
Utah Jazz 2024               0.397260          -1.0
Brooklyn Nets 2024           0.383562          -1.0
Memphis Grizzlies 2024       0.328767          -1.0
Toronto Raptors 2024         0.315068          -1.0
Portland Trail Blazers 2024  0.260274          -1.0
Charlotte Hornets 2024       0.250000          -1.0
San Antonio Spurs 2024       0.232877          -1.0
Detroit Pistons 2024         0.164384          -1.0

FG       FGA       FG%        3P       3PA  \
Team                                                                            
Atlanta Hawks 2024           1.023697  1.040449  0.981053  1.078125  1.074286   
Boston Celtics 2024          1.037915  1.013483  1.023158  1.296875  1.217143   
Brooklyn Nets 2024           0.971564  1.006742  0.962105  1.046875  1.062857   
Charlotte Hornets 2024       0.950237  0.983146  0.964211  0.921875  0.957143   
Chicago Bulls 2024           0.990521  1.006742  0.983158  0.906250  0.928571   
Cleveland Cavaliers 2024     0.988152  0.979775  1.006316  1.062500  1.065714   
Dallas Mavericks 2024        1.028436  1.010112  1.016842  1.140625  1.125714   
Denver Nuggets 2024          1.040284  0.996629  1.042105  0.890625  0.882857   
Detroit Pistons 2024         0.976303  0.993258  0.981053  0.867187  0.908571   
Golden State Warriors 2024   1.035545  1.037079  0.995789  1.148437  1.122857   
Houston Rockets 2024         0.992891  1.020225  0.970526  0.976562  1.011429   
Indiana Pacers 2024          1.106635  1.039326  1.063158  1.039062  1.008571   
Los Angeles Clippers 2024    1.007109  0.971910  1.035789  1.007812  0.951429   
Los Angeles Lakers 2024      1.035545  0.984270  1.048421  0.921875  0.885714   
Memphis Grizzlies 2024       0.907583  0.985393  0.917895  1.046875  1.100000   
Miami Heat 2024              0.938389  0.961798  0.972632  0.953125  0.951429   
Milwaukee Bucks 2024         1.033175  1.000000  1.031579  1.125000  1.094286   
Minnesota Timberwolves 2024  0.978673  0.958427  1.018947  0.992188  0.931429   
New Orleans Pelicans 2024    1.014218  0.983146  1.029474  0.960938  0.925714   
New York Knicks 2024         0.973934  0.996629  0.974737  1.031250  1.031429   
Oklahoma City Thunder 2024   1.056872  1.005618  1.050526  1.046875  0.980000   
Orlando Magic 2024           0.962085  0.953933  1.006316  0.859375  0.891429   
Philadelphia 76ers 2024      0.978673  1.002247  0.974737  0.914062  0.934286   
Phoenix Suns 2024            1.014218  0.968539  1.044211  0.953125  0.914286   
Portland Trail Blazers 2024  0.938389  1.002247  0.934737  0.914062  0.945714   
Sacramento Kings 2024        1.035545  1.022472  1.010526  1.101562  1.108571   
San Antonio Spurs 2024       0.992891  1.019101  0.972632  0.968750  1.025714   
Toronto Raptors 2024         1.007109  1.008989  0.995789  0.906250  0.948571   
Utah Jazz 2024               1.002370  1.014607  0.987368  1.015625  1.048571   
Washington Wizards 2024      1.018957  1.028090  0.989474  0.960938  1.005714   

                                  3P%  ...      ORB%    FT/FGA  Opp eFG%  \
Team                                   ...                                 
Atlanta Hawks 2024           1.000000  ...  1.139918  1.067358  1.043876   
Boston Celtics 2024          1.065574  ...  1.028807  0.968912  0.957952   
Brooklyn Nets 2024           0.989071  ...  1.037037  0.906736  0.996344   
Charlotte Hornets 2024       0.959016  ...  0.897119  0.854922  1.043876   
Chicago Bulls 2024           0.978142  ...  1.020576  0.979275  1.012797   
Cleveland Cavaliers 2024     1.000000  ...  0.962963  0.927461  0.965265   
Dallas Mavericks 2024        1.010929  ...  0.921811  0.994819  1.005484   
Denver Nuggets 2024          1.010929  ...  1.057613  0.896373  0.965265   
Detroit Pistons 2024         0.953552  ...  1.012346  1.020725  1.021938   
Golden State Warriors 2024   1.024590  ...  1.135802  0.896373  0.989031   
Houston Rockets 2024         0.964481  ...  1.037037  1.036269  0.967093   
Indiana Pacers 2024          1.027322  ...  0.967078  0.906736  1.021938   
Los Angeles Clippers 2024    1.057377  ...  1.000000  1.103627  0.996344   
Los Angeles Lakers 2024      1.038251  ...  0.806584  1.124352  1.001828   
Memphis Grizzlies 2024       0.948087  ...  0.946502  0.958549  1.005484   
Miami Heat 2024              1.002732  ...  0.901235  1.088083  1.001828   
Milwaukee Bucks 2024         1.030055  ...  0.893004  1.103627  0.985375  